displayName=Perilous Moons Splits
author=HungryPotato67
description=Tracks split times, personal bests, and supplies used during Moons of Peril trips
tags=moons,perilous moons,neypotzli,boss,splits,timer,pb
plugins=com.perilousmoonssplits.PerilousMoonsSplitsPlugin
version=
build=standard
